### ISSUE TITLE
Readme Doc should have instructions for use of --version

### ISSUE THREAD

**Issue by majorthorn** [canha/golang-tools-install-script#26]
The readme should have a section for how to use --version when piping to bash.

### Example
`wget -q -O - https://raw.githubusercontent.com/canha/golang-tools-install-script/master/goinstall.sh \ | bash -s -- --version 1.13.1
`

**Comment by canha** [comment]
Was just thinking about it when I merged your original PR. If you get to it before me, feel free to submit another PR 😄

**Comment by majorthorn** [comment]
Will do! 😆
