### ISSUE TITLE
Not working correct on Raspberry Pi

### ISSUE THREAD

**Issue by mlgarrido** [canha/golang-tools-install-script#32]
Hello, i made this changes for working right in Raspberry Pi:

- Added a new case for armv7

"armv7")
            ARCH=armv6l
            ;;
        "armv7l")
            ARCH=armv6l
            ;;

- Change download link for: https://dl.google.com/go/

**Comment by canha** [comment]
Hi! Sorry I only got back to this now. Are you sure you don't want to submit a pull request? That way you can contribute properly! :smiley:

**Comment by majorthorn** [comment]
@mlgarrido  What versions of Raspberry Pi will this work on? We need an update for the README.md
