### ISSUE TITLE
consider installing git as dependency for "go get"

### ISSUE THREAD

**Issue by FalcoSuessgott** [canha/golang-tools-install-script#44]
```
$> curl -L https://git.io/vQhTU | bash
$> source /root/.bashr
$> go get -u github.com/cli/cli
go: missing Git command. See https://golang.org/s/gogetcmd
package github.com/cli/cli: exec: "git": executable file not found in $PATH
```

maybe a message would be enough tho

**Comment by canha** [comment]
Hi. Will think about this some more as soon as I can but, I'd say a message sounds quite appropriate, given there are many ways of installing Git in various platforms and it would be expensive to try to cover all cases.

**Comment by FalcoSuessgott** [comment]
Yeah actually I thought about it and I might opened that issue too fast, go is properly installed and now trying to install git for every possible OS would be a huge deal.

A message would be nice to have. But in the end the user should Install it on their own.

closing then and my apologies.
