### ISSUE TITLE
Why is install dir different than the manual installation directory?

### ISSUE THREAD

**Issue by BenRacicot** [canha/golang-tools-install-script#47]
Hello this is a great script but I have a fundamental question.

I see the script sets `GOROOT="$HOME/.go"` for the install dir and `GOROOT` variable.
According to docs "This is usually" `/usr/local/go`

Why this difference?

**Comment by canha** [comment]
Hi @BenRacicot, thanks!

The rationale is that you don't require root privileges to install the tooling. Writing to `/usr/local/go` usually requires elevated permissions.

Hope that clarifies the question, let me know.

**Comment by BenRacicot** [comment]
Ah ok, that makes sense. 

I've been building a script to install several open-source packages and repos. I tested this script and software expecting GOROOT to be in `/usr/local/go` was broken. Just something to think about. 

Please let me know if I can help and thanks for your awesome work on this. :)

**Comment by canha** [comment]
You can use this option https://github.com/canha/golang-tools-install-script/blob/master/README.md#pencil-notes to change the install location!

**Comment by smilinghunter** [comment]
After installing the Golang environment when eve I install GO tools it will show command not found

**Comment by smilinghunter** [comment]
![Screenshot_20210909-223114_Messenger.jpg](https://user-images.githubusercontent.com/72664995/132768565-22ef4a91-1f15-4cb9-9fce-2c34d8d2e5f8.jpg)

**Comment by canha** [comment]
Hi there @smilinghunter. Seems you are installing with root (you don't need to), which means it will, by default, install to the root's $HOME which is /root/. Also don't forget to reload your shell like it says, after the install.
