### ISSUE TITLE
script doesn't parse mkdir properly

### ISSUE THREAD

**Issue by abrahamrhoffman** [canha/golang-tools-install-script#5]
Line 58: mkdir -p "$HOME/go/{src,pkg,bin}"

This actually produces a folder at ~/go/ called "{src,pkg,bin}", not three separate folders.

I suggest changing the line to:

for folder in {src,pkg,bin};do mkdir -p ${folder};done

**Comment by canha** [comment]
That is odd. What version of Bash are you running and in what operating system?

**Comment by abrahamrhoffman** [comment]
GNU bash, version 4.3.11(1)-release (x86_64-pc-linux-gnu)

**Comment by canha** [comment]
Oh wow, thanks for noticing, I'm fixing it right away. :sweat:
