### ISSUE TITLE
Syntax error if `profile` file doesn't have trailing newline

### ISSUE THREAD

**Issue by shellscape** [canha/golang-tools-install-script#68]
Hey thanks for putting this together. Wanted to let you know about a bug that exists when the profile file (e.g. `.zshrc` doesn't have a trailing newline. This script writes Go path variables to the end like so:

```bash
# GoLang
export GOROOT=/Users/user/.go
export PATH=$GOROOT/bin:$PATH
export GOPATH=/Users/user/go
export PATH=$GOPATH/bin:$PATH
```

Say there's no trailing newline in that file and the last line happens to be something like:

```bash
export NODE_OPTIONS="--max-old-space-size=16000"
```

That results in this script writing:

```bash
export NODE_OPTIONS="--max-old-space-size=16000"# GoLang
export GOROOT=/Users/user/.go
export PATH=$GOROOT/bin:$PATH
export GOPATH=/Users/user/go
export PATH=$GOPATH/bin:$PATH
```

Which will cause a `bad option` error for any node apps launching from the console. That likely affects other variables at the end as well.

**Comment by canha** [comment]
Thanks for the suggestion, updated with a new line for the first line :+1:.  At the end we should be OK as we don't manage what comes after.
